/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Console build identity and live capability flags.
         * @description `capabilities` is computed per request from this replica's own realtime pipeline health, never from config: it holds "events" only while the ingester has a proven stream. Always an array, never null.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What this console instance has wired, for frontend feature detection. */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live cluster topology, proxied from the controller.
         * @description The controller's snapshot verbatim. A non-leader reply is retried with backoff; if every attempt still fails the console answers 502.
         */
        get: operations["getTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Node-to-node connectivity matrix, recomputed from Prometheus per request.
         * @description Fail ratio and RTT p95 come from 5m-rate-window queries; loss ratio (udp/icmp only) is an instant average. A pair with no matching series gets a null field rather than a zero. rttP95 is nanoseconds.
         */
        get: operations["getMatrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event history for Live scrollback, newest first.
         * @description Same LiveEvent shape the `live` WebSocket topic delivers, so one type serves both. `nextCursor` is set only when the page came back exactly as full as requested.
         */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/promql/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Guarded passthrough to Prometheus /api/v1/query.
         * @description The response envelope -- success or Prometheus's own error body -- is forwarded byte-for-byte, never re-shaped.
         */
        post: operations["promqlQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/promql/query_range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Guarded passthrough to Prometheus /api/v1/query_range.
         * @description `step` is nanoseconds in this request (the client converts to Prometheus's seconds). A range wider than prometheus.maxRange, or a result over prometheus.maxResponseBytes, is 422.
         */
        post: operations["promqlQueryRange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run history, newest first. */
        get: operations["listRuns"];
        put?: never;
        /**
         * Start a diagnostics run (asynchronous).
         * @description Fan-out over sources x destinations -- full mesh, or one-sided when either is empty, resolved against live topology -- bounded to 400 pairs after self-pair exclusion. A malformed body or unknown type is 400; a well-formed spec refused for what it would produce (too many pairs, no pairs, no nodes) is 422.
         */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /**
         * One run's summary plus its per-pair results.
         * @description Also the documented REST-polling fallback when the run's `run:{id}` WebSocket topic is unavailable.
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a run in flight.
         * @description Requires runs:create -- starting fleet-wide probe traffic and stopping it are the same operational class. Cancellation is asynchronous: pairs already dispatched still record their outcome, pairs not yet dispatched never dispatch, and the run reaches status `cancelled`. Read the final state from GET /api/v1/runs/{id}. Cancelling a run that already finished, or one another replica started, is a no-op that also answers 204 -- the stuck-run reaper is what eventually finishes a run no replica still holds.
         */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One page of external probe targets, newest first. */
        get: operations["listTargets"];
        put?: never;
        /**
         * Create one target.
         * @description A duplicate name is 422, not 409: it is a rejected field value in an otherwise well-formed body.
         */
        post: operations["createTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/targets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /** One target. An unknown id and a malformed one are both 404. */
        get: operations["getTarget"];
        /** Replace one target in full (an omitted field means empty, never "leave as-is"). */
        put: operations["updateTarget"];
        post?: never;
        /** Delete one target; 409 while any check definition still references it. */
        delete: operations["deleteTarget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One page of check definitions, newest first. */
        get: operations["listCheckDefinitions"];
        put?: never;
        /**
         * Create one check definition.
         * @description The projection guard runs before the write and only for a definition arriving enabled: over the 400-series limit it is 422, while the same definition saved with "enabled": false is accepted.
         */
        post: operations["createCheckDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checks/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * What a draft definition WOULD project against the live topology.
         * @description Persists nothing. Same function, same limit the create/update guard uses, so the number the UI shows can never disagree with enforcement. Gated on checks:write, not checks:read -- the body is a draft definition, and a caller who cannot create one has no question to ask.
         */
        post: operations["projectCheckDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /** One check definition. An unknown id and a malformed one are both 404. */
        get: operations["getCheckDefinition"];
        /** Replace one check definition in full. */
        put: operations["updateCheckDefinition"];
        post?: never;
        /** Delete one check definition; its schedules cascade with it. */
        delete: operations["deleteCheckDefinition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One page of schedules. */
        get: operations["listSchedules"];
        put?: never;
        /**
         * Create one schedule.
         * @description kind "cron" is refused with a 422 naming the milestone it lands in, rather than degrading into a generic enum error. An interval below 10s is clamped up, and the response is the stored row, so a client that asked for 1s is told it got 10s.
         */
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        /** One schedule. An unknown id and a malformed one are both 404. */
        get: operations["getSchedule"];
        /**
         * Replace one schedule's cadence in full.
         * @description definitionId is not updatable: a body naming a different definition is refused with 422 rather than silently ignored.
         */
        put: operations["updateSchedule"];
        post?: never;
        /** Delete one schedule. Nothing references a schedule, so there is no 409. */
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit log, newest first.
         * @description `detail` is whatever the per-route allow-list let through -- {} for almost everything (SECURITY.md, "The audit log's documented lossiness").
         */
        get: operations["listAuditEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rbac/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The static, compiled-in permission list.
         * @description Needs no database and is therefore always available, unlike the rest of /api/v1/rbac.
         */
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rbac/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Custom roles (built-ins are compiled in and not listed here). */
        get: operations["listRoles"];
        put?: never;
        /**
         * Create or replace one custom role.
         * @description 422 for a name colliding with a built-in (viewer, operator, alert-editor, admin) or for a permission outside the compiled-in list.
         */
        post: operations["upsertRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rbac/roles/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Custom role name. */
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete one custom role; 409 while any binding still references it. */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rbac/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every role binding. */
        get: operations["listBindings"];
        put?: never;
        /**
         * Bind a subject to a role.
         * @description 422 for a subjectKind outside user/group (token bindings are declared in the schema but resolved by nothing, so storing one would silently grant nothing) or for an unknown role name; 409 on a duplicate.
         */
        post: operations["createBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rbac/bindings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Binding id. A non-integer is 400. */
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete one role binding. */
        delete: operations["deleteBinding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Token metadata -- never the hash, never the secret. */
        get: operations["listTokens"];
        put?: never;
        /**
         * Mint a token.
         * @description The response is the only place the raw wire-form token (kcm_...) is ever returned; it is never stored or logged. Served with Cache-Control: no-store.
         */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one token; 404 for an unknown or already-revoked id. */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's resolved identity and effective permissions.
         * @description The ROUTE is public -- the UI must be able to call it before it knows whether it is logged in -- but the HANDLER still needs a resolved identity: 401 when nothing resolved, which never happens under auth.mode=anonymous.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Password login; auth.mode=local only.
         * @description 404 in every other mode, so the UI feature-detects the login affordance instead of hardcoding auth.mode's cases. Unknown user, disabled account and wrong password are indistinguishable by status, body AND timing. On success sets the session and CSRF cookies.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete the session server-side and clear both cookies.
         * @description Mode-agnostic and idempotent -- safe with no session cookie at all.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect to the IdP authorization endpoint; auth.mode=oidc only.
         * @description Full-page navigation, not fetch. 404 in every other mode.
         */
        get: operations["oidcStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consume the IdP redirect, mint a session, redirect to returnTo.
         * @description Browser-facing, not a JSON endpoint. auth.mode=oidc only; 404 otherwise. returnTo is re-validated after its round trip through the state store, so a corrupted stash can never become an open redirect.
         */
        get: operations["oidcCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 error body. `type` is always "about:blank" so far. */
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
        };
        /**
         * @default tcp
         * @enum {string}
         */
        Protocol: "tcp" | "udp" | "icmp";
        /**
         * @description A definition names exactly one of these.
         * @enum {string}
         */
        CheckType: "tcp" | "udp" | "icmp" | "dns" | "http" | "mtr";
        /** @enum {string} */
        RunStatus: "pending" | "running" | "succeeded" | "failed" | "partial" | "cancelled";
        /** @enum {string} */
        SubjectKind: "anonymous" | "user" | "token";
        /** @enum {string} */
        LiveEventType: "topology_changed" | "check_observed" | "mtr_triggered" | "mtr_completed" | "diagnostic_progress";
        /** @enum {string} */
        LiveEventSeverity: "info" | "warn" | "error";
        Version: {
            /** @description The console BINARY's version, not the Helm chart's. */
            version: string;
            commit: string;
            /** @description Always an array, never null. Holds "events" while this replica's pipeline is healthy. */
            capabilities: string[];
        };
        Config: {
            auth: {
                /** @enum {string} */
                mode: "anonymous" | "local" | "header" | "oidc";
                /** @description auth.anonymous.role -- what an unauthenticated caller gets. */
                role: string;
                /** @description Endpoint that starts this mode's login flow; empty when the mode has none. */
                loginPath: string;
            };
            anonymousBanner: boolean;
            controller: components["schemas"]["ConfiguredFlag"];
            prometheus: components["schemas"]["ConfiguredFlag"];
            database: components["schemas"]["ConfiguredFlag"];
        };
        ConfiguredFlag: {
            configured: boolean;
        };
        TopologyNode: {
            name: string;
            zone: string;
            ready: boolean;
        };
        TopologyAgent: {
            id: string;
            nodeName: string;
            podIP: string;
            zone: string;
        };
        Topology: {
            nodes: components["schemas"]["TopologyNode"][];
            agents: components["schemas"]["TopologyAgent"][];
            /** Format: date-time */
            timestamp: string;
        };
        MatrixCell: {
            source: string;
            destination: string;
            /** @description null when no series matched the pair -- not a zero. */
            failRatio: number | null;
            /**
             * Format: int64
             * @description Nanoseconds. Omitted when no series matched.
             */
            rttP95?: number;
            /** @description udp/icmp only. Omitted when no series matched. */
            lossRatio?: number;
        };
        Matrix: {
            protocol: components["schemas"]["Protocol"];
            plane: string;
            nodes: string[];
            cells: components["schemas"]["MatrixCell"][];
            /** Format: date-time */
            timestamp: string;
        };
        PromQLQueryRequest: {
            query: string;
            /**
             * Format: date-time
             * @description RFC3339; omitted means "now".
             */
            time?: string;
        };
        PromQLRangeRequest: {
            query: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            /**
             * Format: int64
             * @description Nanoseconds (repo-wide convention) -- note this differs from Prometheus's own API, which takes seconds; the client converts.
             */
            step: number;
        };
        /** @description Prometheus's own envelope, forwarded byte-for-byte. Modelled loosely on purpose: the console never re-shapes it, so pinning it here would promise a stability the upstream does not. */
        PromResult: {
            /** @enum {string} */
            status: "success" | "error";
            data?: {
                [key: string]: unknown;
            };
            errorType?: string;
            error?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Browser-facing projection of the controller's event. `id` is "<seq>-<unixNano>" and identical on every replica, which is what makes it both the hub's dedupe key and a stable React list key. */
        LiveEvent: {
            id: string;
            /**
             * Format: int64
             * @description Controller-assigned and gapless per controller; a gap here is the loss signal.
             */
            seq: number;
            type: components["schemas"]["LiveEventType"];
            severity: components["schemas"]["LiveEventSeverity"];
            scope: string;
            /** Format: date-time */
            timestamp: string;
            summary: string;
            /** @description Type-specific payload; see WEBSOCKET.md "Payloads". */
            details: {
                [key: string]: unknown;
            };
        };
        EventPage: {
            events: components["schemas"]["LiveEvent"][];
            /** @description Empty string when the page proves nothing older is left. */
            nextCursor: string;
        };
        RunCreateRequest: {
            /** @description Empty or absent means every node in the current topology. */
            sources?: string[];
            destinations?: string[];
            type: components["schemas"]["CheckType"];
            plane?: string;
            /**
             * Format: int64
             * @description Per-pair timeout in nanoseconds; unset lets the server apply its own default and clamp.
             */
            timeoutNs?: number;
            /**
             * @description node (default) keeps destinations as node names, the pre-M4 contract. target resolves a saved target row (destinationTargetId); adhoc probes destinationAddress. Both external kinds require destinations to be empty.
             * @enum {string}
             */
            destinationKind?: "node" | "target" | "adhoc";
            /**
             * Format: uuid
             * @description Required when destinationKind is target.
             */
            destinationTargetId?: string;
            /** @description Required when destinationKind is adhoc. */
            destinationAddress?: string;
        };
        RunCreateResponse: {
            id: string;
            status: components["schemas"]["RunStatus"];
            pairTotal: number;
            /** @description Server-chosen topic name; subscribe to what you were told, never a string you built. */
            wsTopic: string;
        };
        RunSummary: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            status: components["schemas"]["RunStatus"];
            type: string;
            plane: string;
            initiatorKind: string;
            initiatorId: string;
            pairTotal: number;
            pairOk: number;
            pairFailed: number;
        };
        RunResult: {
            sourceNode: string;
            destinationNode: string;
            success: boolean;
            /** Format: int64 */
            durationNs: number;
            error?: string;
            /** @description Check-type-specific payload, stored verbatim. */
            result?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            recordedAt: string;
        };
        /** @description One run's summary plus its spec snapshot and per-pair results. */
        RunDetail: components["schemas"]["RunSummary"] & {
            /** @description The run's spec as submitted, snapshotted at creation. */
            spec: {
                [key: string]: unknown;
            };
            results: components["schemas"]["RunResult"][];
        };
        RunPage: {
            runs: components["schemas"]["RunSummary"][];
            nextCursor: string;
        };
        /** @enum {string} */
        TargetKind: "host" | "url";
        Target: {
            /** Format: uuid */
            id: string;
            /** @description Becomes a Prometheus label value, hence the restricted charset store enforces. */
            name: string;
            kind: components["schemas"]["TargetKind"];
            address: string;
            /** @description Always an object ({} when unset), never null. */
            labels: {
                [key: string]: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Create and update body; a FULL replace -- an omitted field means empty. */
        TargetRequest: {
            name: string;
            kind: components["schemas"]["TargetKind"];
            address: string;
            labels?: {
                [key: string]: string;
            };
        };
        TargetPage: {
            targets: components["schemas"]["Target"][];
            nextCursor: string;
        };
        /**
         * @description How the definition picks the agents that run it. "all" and "per-zone" both resolve to every agent -- per-zone groups them rather than shrinking the set; only "one-per-zone" reduces the count, which is why it is the default.
         * @enum {string}
         */
        SourceSelection: "all" | "per-zone" | "one-per-zone";
        /** @enum {string} */
        DestinationKind: "node" | "target" | "adhoc";
        CheckDefinition: {
            /** Format: uuid */
            id: string;
            name: string;
            sourceSelection: components["schemas"]["SourceSelection"];
            destinationKind: components["schemas"]["DestinationKind"];
            /** @description Empty unless destinationKind is "target". */
            destinationTargetId: string;
            /** @description Empty unless destinationKind is "adhoc". */
            destinationAddress: string;
            checkType: components["schemas"]["CheckType"];
            plane: string;
            /** @description Always an object ({} when unset), never null. */
            params: {
                [key: string]: unknown;
            };
            enabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Create, update AND projection body -- the projection endpoint reads the same shape so the UI can send the form it is about to submit, unchanged. Create/update are FULL replaces. */
        CheckDefinitionRequest: {
            name: string;
            sourceSelection: components["schemas"]["SourceSelection"];
            destinationKind: components["schemas"]["DestinationKind"];
            /** Format: uuid */
            destinationTargetId?: string;
            destinationAddress?: string;
            checkType: components["schemas"]["CheckType"];
            plane: string;
            params?: {
                [key: string]: unknown;
            };
            enabled?: boolean;
        };
        CheckDefinitionPage: {
            definitions: components["schemas"]["CheckDefinition"][];
            nextCursor: string;
        };
        /** @description What ONE definition would project against the CURRENT topology, so the same definition can project differently as the cluster scales. The bound is per definition, never fleet-wide. */
        Projection: {
            agents: number;
            /** @description 1 today -- a definition names exactly one check type. */
            protocols: number;
            /** @description agents x protocols. */
            series: number;
            /** @description 400, the same bound the diagnostics runner applies to one run's fan-out. */
            limit: number;
            /** @description True means enabling this definition is refused with 422. */
            overLimit: boolean;
        };
        /**
         * @description "cron" is deliberately absent: it is refused with a 422 naming the milestone it lands in, not silently treated as an enum typo.
         * @enum {string}
         */
        ScheduleKind: "once" | "interval" | "continuous";
        Schedule: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            definitionId: string;
            kind: components["schemas"]["ScheduleKind"];
            /**
             * Format: int64
             * @description Nanoseconds; clamped up to 10s for kind "interval".
             */
            intervalNs: number;
            /** Format: date-time */
            runAt: string | null;
            enabled: boolean;
            /**
             * Format: date-time
             * @description null means this schedule has never fired -- a zero timestamp would read as year 1.
             */
            lastFiredAt: string | null;
            /**
             * Format: date-time
             * @description Scheduler bookkeeping; null for kind "continuous", which the loop never fires.
             */
            nextFireAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Full replace. nextFireAt is deliberately absent -- it is scheduler bookkeeping, and letting a client write it would let it schedule a fire in the past and stampede the loop. definitionId is not updatable. */
        ScheduleRequest: {
            /** Format: uuid */
            definitionId: string;
            kind: components["schemas"]["ScheduleKind"];
            /**
             * Format: int64
             * @description Required for kind "interval"; must be absent for the others.
             */
            intervalNs?: number;
            /**
             * Format: date-time
             * @description Required for kind "once", and must be in the future.
             */
            runAt?: string;
            enabled?: boolean;
        };
        SchedulePage: {
            schedules: components["schemas"]["Schedule"][];
            nextCursor: string;
        };
        AuditEntry: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            at: string;
            subjectKind: string;
            subjectId: string;
            /** @description Method plus route pattern, e.g. "POST /api/v1/runs". */
            action: string;
            resource: string;
            /** @enum {string} */
            outcome: "allowed" | "denied" | "error";
            remoteAddr: string;
            /** @description Whatever the per-route allow-list let through; {} for almost everything. */
            detail: {
                [key: string]: unknown;
            };
        };
        AuditPage: {
            entries: components["schemas"]["AuditEntry"][];
            nextCursor: string;
        };
        PermissionList: {
            permissions: string[];
        };
        Role: {
            name: string;
            permissions: string[];
        };
        RoleRequest: {
            /** @description May not collide with a built-in (viewer, operator, alert-editor, admin). */
            name: string;
            permissions: string[];
        };
        RoleList: {
            roles: components["schemas"]["Role"][];
        };
        Binding: {
            /** Format: int64 */
            id: number;
            roleName: string;
            subjectKind: string;
            subjectId: string;
        };
        BindingRequest: {
            roleName: string;
            /** @enum {string} */
            subjectKind: "user" | "group";
            subjectId: string;
        };
        BindingList: {
            bindings: components["schemas"]["Binding"][];
        };
        /** @description Token metadata. Structurally carries no hash and no secret. */
        Token: {
            id: string;
            name: string;
            owner: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
            /** Format: date-time */
            revokedAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        TokenList: {
            tokens: components["schemas"]["Token"][];
        };
        TokenCreateRequest: {
            name: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        TokenCreateResponse: {
            id: string;
            name: string;
            /** @description The raw wire-form token (kcm_...), returned exactly once and never again. */
            token: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        MeSubject: {
            kind: components["schemas"]["SubjectKind"];
            id: string;
            displayName: string;
            groups: string[];
            roles: string[];
        };
        Me: {
            subject: components["schemas"]["MeSubject"];
            /** @description The flattened, already-resolved permission list -- never role names to re-resolve. */
            permissions: string[];
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
    };
    responses: {
        /** @description Done; no body. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Malformed request -- unparseable body, bad filter value, or a broken cursor. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No credentials resolved for a route that needs a permission. */
        Unauthorized: {
            headers: {
                /** @description Always "Bearer". */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated but missing the permission this route requires, or a cookie-authenticated mutation without a valid CSRF double-submit pair. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource, or the endpoint is not offered in this auth mode. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Refused because of the state of OTHER rows (something still references this one). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Well-formed body whose VALUES were rejected -- never a parse failure. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Server-side failure; the detail is deliberately empty. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description An upstream (controller, Prometheus, database) could not be reached or refused. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The dependency this route needs is not configured. The detail names the config value that enables it. */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Page size, clamped into [1,500]. An unparseable value is treated as unset. */
        Limit: number;
        /** @description Opaque keyset cursor from the previous page's nextCursor. Malformed, or minted by another server, is 400. */
        Cursor: string;
        /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
        PathID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature-detection snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
        };
    };
    getTopology: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topology snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topology"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    getMatrix: {
        parameters: {
            query?: {
                /** @description Probe protocol. Anything outside the enum is 400. */
                protocol?: components["schemas"]["Protocol"];
                /** @description Only "pod" exists so far; anything else is 400. */
                plane?: "pod";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matrix snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Matrix"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description Repeatable. An unknown event type is 400. */
                type?: components["schemas"]["LiveEventType"][];
                /** @description Exact match on the event's scope. */
                scope?: string;
                /** @description RFC3339. Must precede `to`. */
                from?: string;
                to?: string;
                /** @description Page size, clamped into [1,500]. An unparseable value is treated as unset. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from the previous page's nextCursor. Malformed, or minted by another server, is 400. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    promqlQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromQLQueryRequest"];
            };
        };
        responses: {
            /** @description Prometheus's own response envelope, forwarded verbatim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    promqlQueryRange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromQLRangeRequest"];
            };
        };
        responses: {
            /** @description Prometheus's own response envelope, forwarded verbatim. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                type?: components["schemas"]["CheckType"];
                status?: components["schemas"]["RunStatus"];
                /** @description Page size, clamped into [1,500]. An unparseable value is treated as unset. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from the previous page's nextCursor. Malformed, or minted by another server, is 400. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Run accepted and started. */
            202: {
                headers: {
                    /** @description Permalink to the run. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation accepted (or the run was already terminal). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    listTargets: {
        parameters: {
            query?: {
                kind?: components["schemas"]["TargetKind"];
                /** @description Page size, clamped into [1,500]. An unparseable value is treated as unset. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from the previous page's nextCursor. Malformed, or minted by another server, is 400. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of targets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    createTarget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetRequest"];
            };
        };
        responses: {
            /** @description Target created. */
            201: {
                headers: {
                    /** @description Permalink to the new target. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    getTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The target. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetRequest"];
            };
        };
        responses: {
            /** @description The stored row after the write, not an echo of the request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Target"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    listCheckDefinitions: {
        parameters: {
            query?: {
                /** @description Must be a UUID; a typo is 400, never 502. */
                targetId?: string;
                /** @description Anything other than "true"/"false" is treated as unset. */
                enabled?: boolean;
                /** @description Page size, clamped into [1,500]. An unparseable value is treated as unset. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from the previous page's nextCursor. Malformed, or minted by another server, is 400. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of check definitions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDefinitionPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    createCheckDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckDefinitionRequest"];
            };
        };
        responses: {
            /** @description Check definition created. */
            201: {
                headers: {
                    /** @description Permalink to the new definition. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDefinition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    projectCheckDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckDefinitionRequest"];
            };
        };
        responses: {
            /** @description The projection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Projection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    getCheckDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The check definition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDefinition"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateCheckDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckDefinitionRequest"];
            };
        };
        responses: {
            /** @description The stored row after the write. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDefinition"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteCheckDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    listSchedules: {
        parameters: {
            query?: {
                /** @description Must be a UUID; a typo is 400, never 502. */
                definitionId?: string;
                /** @description Page size, clamped into [1,500]. An unparseable value is treated as unset. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from the previous page's nextCursor. Malformed, or minted by another server, is 400. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of schedules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            /** @description Schedule created. */
            201: {
                headers: {
                    /** @description Permalink to the new schedule. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The schedule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleRequest"];
            };
        };
        responses: {
            /** @description The stored row after the write. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    listAuditEntries: {
        parameters: {
            query?: {
                subjectKind?: components["schemas"]["SubjectKind"];
                subjectId?: string;
                /** @description Page size, clamped into [1,500]. An unparseable value is treated as unset. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor from the previous page's nextCursor. Malformed, or minted by another server, is 400. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every permission string the policy engine knows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom roles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    upsertRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description The stored role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Custom role name. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    listBindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role bindings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindingList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    createBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindingRequest"];
            };
        };
        responses: {
            /** @description The stored binding. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Binding"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Binding id. A non-integer is 400. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every token's metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenCreateRequest"];
            };
        };
        responses: {
            /** @description The minted token, secret included exactly once. */
            200: {
                headers: {
                    /** @description Always "no-store" on this response. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenCreateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource id (UUID). A malformed id is 404, indistinguishable from an unknown one. */
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Who the caller is. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in; session and CSRF cookies set. */
            204: {
                headers: {
                    /** @description Session cookie, then the CSRF cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    /** @description Both cookies cleared. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oidcStart: {
        parameters: {
            query?: {
                /** @description Must be a same-origin relative path; anything else is 400. */
                returnTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the IdP. */
            302: {
                headers: {
                    /** @description The IdP authorization URL. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    oidcCallback: {
        parameters: {
            query: {
                state: string;
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session minted; redirect to the stashed returnTo. */
            302: {
                headers: {
                    /** @description Same-origin relative path. */
                    Location?: string;
                    /** @description Session cookie, then the CSRF cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
