{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kconmon-ng.serviceAccountName" . }}
  labels:
    {{- include "kconmon-ng.labels" . | nindent 4 }}
{{- end }}
