// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kconmon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerUpdate_UpdateType int32

const (
	PeerUpdate_FULL_SYNC    PeerUpdate_UpdateType = 0
	PeerUpdate_PEER_ADDED   PeerUpdate_UpdateType = 1
	PeerUpdate_PEER_REMOVED PeerUpdate_UpdateType = 2
)

// Enum value maps for PeerUpdate_UpdateType.
var (
	PeerUpdate_UpdateType_name = map[int32]string{
		0: "FULL_SYNC",
		1: "PEER_ADDED",
		2: "PEER_REMOVED",
	}
	PeerUpdate_UpdateType_value = map[string]int32{
		"FULL_SYNC":    0,
		"PEER_ADDED":   1,
		"PEER_REMOVED": 2,
	}
)

func (x PeerUpdate_UpdateType) Enum() *PeerUpdate_UpdateType {
	p := new(PeerUpdate_UpdateType)
	*p = x
	return p
}

func (x PeerUpdate_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerUpdate_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_kconmon_proto_enumTypes[0].Descriptor()
}

func (PeerUpdate_UpdateType) Type() protoreflect.EnumType {
	return &file_kconmon_proto_enumTypes[0]
}

func (x PeerUpdate_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerUpdate_UpdateType.Descriptor instead.
func (PeerUpdate_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{5, 0}
}

type AgentMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodIp         string                 `protobuf:"bytes,4,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	Zone          string                 `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMeta) Reset() {
	*x = AgentMeta{}
	mi := &file_kconmon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMeta) ProtoMessage() {}

func (x *AgentMeta) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMeta.ProtoReflect.Descriptor instead.
func (*AgentMeta) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentMeta) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AgentMeta) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AgentMeta) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *AgentMeta) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *AgentMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentMeta             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_kconmon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetAgent() *AgentMeta {
	if x != nil {
		return x.Agent
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Peers         []*AgentMeta           `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_kconmon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetPeers() []*AgentMeta {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RegisterResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_kconmon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type WatchPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPeersRequest) Reset() {
	*x = WatchPeersRequest{}
	mi := &file_kconmon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPeersRequest) ProtoMessage() {}

func (x *WatchPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPeersRequest.ProtoReflect.Descriptor instead.
func (*WatchPeersRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{4}
}

func (x *WatchPeersRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type PeerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PeerUpdate_UpdateType  `protobuf:"varint,1,opt,name=type,proto3,enum=kconmonng.v1.PeerUpdate_UpdateType" json:"type,omitempty"`
	Peers         []*AgentMeta           `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUpdate) Reset() {
	*x = PeerUpdate{}
	mi := &file_kconmon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUpdate) ProtoMessage() {}

func (x *PeerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUpdate.ProtoReflect.Descriptor instead.
func (*PeerUpdate) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{5}
}

func (x *PeerUpdate) GetType() PeerUpdate_UpdateType {
	if x != nil {
		return x.Type
	}
	return PeerUpdate_FULL_SYNC
}

func (x *PeerUpdate) GetPeers() []*AgentMeta {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeerUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TCPProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceAgentId string                 `protobuf:"bytes,1,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPProbeRequest) Reset() {
	*x = TCPProbeRequest{}
	mi := &file_kconmon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPProbeRequest) ProtoMessage() {}

func (x *TCPProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPProbeRequest.ProtoReflect.Descriptor instead.
func (*TCPProbeRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{6}
}

func (x *TCPProbeRequest) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *TCPProbeRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TCPProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPProbeResponse) Reset() {
	*x = TCPProbeResponse{}
	mi := &file_kconmon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPProbeResponse) ProtoMessage() {}

func (x *TCPProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPProbeResponse.ProtoReflect.Descriptor instead.
func (*TCPProbeResponse) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{7}
}

func (x *TCPProbeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TCPProbeResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UDPProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceAgentId string                 `protobuf:"bytes,1,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	Sequence      uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPProbeRequest) Reset() {
	*x = UDPProbeRequest{}
	mi := &file_kconmon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPProbeRequest) ProtoMessage() {}

func (x *UDPProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPProbeRequest.ProtoReflect.Descriptor instead.
func (*UDPProbeRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{8}
}

func (x *UDPProbeRequest) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *UDPProbeRequest) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *UDPProbeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UDPProbeRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UDPProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint32                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPProbeResponse) Reset() {
	*x = UDPProbeResponse{}
	mi := &file_kconmon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPProbeResponse) ProtoMessage() {}

func (x *UDPProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPProbeResponse.ProtoReflect.Descriptor instead.
func (*UDPProbeResponse) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{9}
}

func (x *UDPProbeResponse) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *UDPProbeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UDPProbeResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_kconmon_proto protoreflect.FileDescriptor

const file_kconmon_proto_rawDesc = "" +
	"\n" +
	"\rkconmon.proto\x12\fkconmonng.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf6\x01\n" +
	"\tAgentMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x15\n" +
	"\x06pod_ip\x18\x04 \x01(\tR\x05podIp\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\tR\x04zone\x12;\n" +
	"\x06labels\x18\x06 \x03(\v2#.kconmonng.v1.AgentMeta.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x0fRegisterRequest\x12-\n" +
	"\x05agent\x18\x01 \x01(\v2\x17.kconmonng.v1.AgentMetaR\x05agent\"\x99\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12-\n" +
	"\x05peers\x18\x02 \x03(\v2\x17.kconmonng.v1.AgentMetaR\x05peers\x12;\n" +
	"\vserver_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"g\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\".\n" +
	"\x11WatchPeersRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xed\x01\n" +
	"\n" +
	"PeerUpdate\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.kconmonng.v1.PeerUpdate.UpdateTypeR\x04type\x12-\n" +
	"\x05peers\x18\x02 \x03(\v2\x17.kconmonng.v1.AgentMetaR\x05peers\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"=\n" +
	"\n" +
	"UpdateType\x12\r\n" +
	"\tFULL_SYNC\x10\x00\x12\x0e\n" +
	"\n" +
	"PEER_ADDED\x10\x01\x12\x10\n" +
	"\fPEER_REMOVED\x10\x02\"s\n" +
	"\x0fTCPProbeRequest\x12&\n" +
	"\x0fsource_agent_id\x18\x01 \x01(\tR\rsourceAgentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\\\n" +
	"\x10TCPProbeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa9\x01\n" +
	"\x0fUDPProbeRequest\x12&\n" +
	"\x0fsource_agent_id\x18\x01 \x01(\tR\rsourceAgentId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x82\x01\n" +
	"\x10UDPProbeResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xea\x01\n" +
	"\rAgentRegistry\x12I\n" +
	"\bRegister\x12\x1d.kconmonng.v1.RegisterRequest\x1a\x1e.kconmonng.v1.RegisterResponse\x12C\n" +
	"\tHeartbeat\x12\x1e.kconmonng.v1.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\n" +
	"WatchPeers\x12\x1f.kconmonng.v1.WatchPeersRequest\x1a\x18.kconmonng.v1.PeerUpdate0\x012\xa4\x01\n" +
	"\fProbeService\x12I\n" +
	"\bTCPProbe\x12\x1d.kconmonng.v1.TCPProbeRequest\x1a\x1e.kconmonng.v1.TCPProbeResponse\x12I\n" +
	"\bUDPProbe\x12\x1d.kconmonng.v1.UDPProbeRequest\x1a\x1e.kconmonng.v1.UDPProbeResponseB1Z/github.com/EsDmitrii/kconmon-ng/api/proto;protob\x06proto3"

var (
	file_kconmon_proto_rawDescOnce sync.Once
	file_kconmon_proto_rawDescData []byte
)

func file_kconmon_proto_rawDescGZIP() []byte {
	file_kconmon_proto_rawDescOnce.Do(func() {
		file_kconmon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kconmon_proto_rawDesc), len(file_kconmon_proto_rawDesc)))
	})
	return file_kconmon_proto_rawDescData
}

var file_kconmon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kconmon_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_kconmon_proto_goTypes = []any{
	(PeerUpdate_UpdateType)(0),    // 0: kconmonng.v1.PeerUpdate.UpdateType
	(*AgentMeta)(nil),             // 1: kconmonng.v1.AgentMeta
	(*RegisterRequest)(nil),       // 2: kconmonng.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 3: kconmonng.v1.RegisterResponse
	(*HeartbeatRequest)(nil),      // 4: kconmonng.v1.HeartbeatRequest
	(*WatchPeersRequest)(nil),     // 5: kconmonng.v1.WatchPeersRequest
	(*PeerUpdate)(nil),            // 6: kconmonng.v1.PeerUpdate
	(*TCPProbeRequest)(nil),       // 7: kconmonng.v1.TCPProbeRequest
	(*TCPProbeResponse)(nil),      // 8: kconmonng.v1.TCPProbeResponse
	(*UDPProbeRequest)(nil),       // 9: kconmonng.v1.UDPProbeRequest
	(*UDPProbeResponse)(nil),      // 10: kconmonng.v1.UDPProbeResponse
	nil,                           // 11: kconmonng.v1.AgentMeta.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_kconmon_proto_depIdxs = []int32{
	11, // 0: kconmonng.v1.AgentMeta.labels:type_name -> kconmonng.v1.AgentMeta.LabelsEntry
	1,  // 1: kconmonng.v1.RegisterRequest.agent:type_name -> kconmonng.v1.AgentMeta
	1,  // 2: kconmonng.v1.RegisterResponse.peers:type_name -> kconmonng.v1.AgentMeta
	12, // 3: kconmonng.v1.RegisterResponse.server_time:type_name -> google.protobuf.Timestamp
	12, // 4: kconmonng.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 5: kconmonng.v1.PeerUpdate.type:type_name -> kconmonng.v1.PeerUpdate.UpdateType
	1,  // 6: kconmonng.v1.PeerUpdate.peers:type_name -> kconmonng.v1.AgentMeta
	12, // 7: kconmonng.v1.PeerUpdate.timestamp:type_name -> google.protobuf.Timestamp
	12, // 8: kconmonng.v1.TCPProbeRequest.timestamp:type_name -> google.protobuf.Timestamp
	12, // 9: kconmonng.v1.TCPProbeResponse.timestamp:type_name -> google.protobuf.Timestamp
	12, // 10: kconmonng.v1.UDPProbeRequest.timestamp:type_name -> google.protobuf.Timestamp
	12, // 11: kconmonng.v1.UDPProbeResponse.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 12: kconmonng.v1.AgentRegistry.Register:input_type -> kconmonng.v1.RegisterRequest
	4,  // 13: kconmonng.v1.AgentRegistry.Heartbeat:input_type -> kconmonng.v1.HeartbeatRequest
	5,  // 14: kconmonng.v1.AgentRegistry.WatchPeers:input_type -> kconmonng.v1.WatchPeersRequest
	7,  // 15: kconmonng.v1.ProbeService.TCPProbe:input_type -> kconmonng.v1.TCPProbeRequest
	9,  // 16: kconmonng.v1.ProbeService.UDPProbe:input_type -> kconmonng.v1.UDPProbeRequest
	3,  // 17: kconmonng.v1.AgentRegistry.Register:output_type -> kconmonng.v1.RegisterResponse
	13, // 18: kconmonng.v1.AgentRegistry.Heartbeat:output_type -> google.protobuf.Empty
	6,  // 19: kconmonng.v1.AgentRegistry.WatchPeers:output_type -> kconmonng.v1.PeerUpdate
	8,  // 20: kconmonng.v1.ProbeService.TCPProbe:output_type -> kconmonng.v1.TCPProbeResponse
	10, // 21: kconmonng.v1.ProbeService.UDPProbe:output_type -> kconmonng.v1.UDPProbeResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_kconmon_proto_init() }
func file_kconmon_proto_init() {
	if File_kconmon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kconmon_proto_rawDesc), len(file_kconmon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kconmon_proto_goTypes,
		DependencyIndexes: file_kconmon_proto_depIdxs,
		EnumInfos:         file_kconmon_proto_enumTypes,
		MessageInfos:      file_kconmon_proto_msgTypes,
	}.Build()
	File_kconmon_proto = out.File
	file_kconmon_proto_goTypes = nil
	file_kconmon_proto_depIdxs = nil
}
