// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kconmon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerUpdate_UpdateType int32

const (
	PeerUpdate_FULL_SYNC    PeerUpdate_UpdateType = 0
	PeerUpdate_PEER_ADDED   PeerUpdate_UpdateType = 1
	PeerUpdate_PEER_REMOVED PeerUpdate_UpdateType = 2
)

// Enum value maps for PeerUpdate_UpdateType.
var (
	PeerUpdate_UpdateType_name = map[int32]string{
		0: "FULL_SYNC",
		1: "PEER_ADDED",
		2: "PEER_REMOVED",
	}
	PeerUpdate_UpdateType_value = map[string]int32{
		"FULL_SYNC":    0,
		"PEER_ADDED":   1,
		"PEER_REMOVED": 2,
	}
)

func (x PeerUpdate_UpdateType) Enum() *PeerUpdate_UpdateType {
	p := new(PeerUpdate_UpdateType)
	*p = x
	return p
}

func (x PeerUpdate_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerUpdate_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_kconmon_proto_enumTypes[0].Descriptor()
}

func (PeerUpdate_UpdateType) Type() protoreflect.EnumType {
	return &file_kconmon_proto_enumTypes[0]
}

func (x PeerUpdate_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerUpdate_UpdateType.Descriptor instead.
func (PeerUpdate_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{6, 0}
}

type AgentMeta struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeName string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodName  string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodIp    string                 `protobuf:"bytes,4,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	Zone     string                 `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	Labels   map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// capabilities are opt-in feature flags this agent build supports, e.g.
	// "external-checks". A pre-M4 agent sends an empty list and the controller
	// refuses to dispatch anything that needs one, rather than sending a field
	// the old agent silently ignores (which would make it probe an empty
	// AgentMeta). Same posture as the Console/controller /api/v1/version
	// capability array: feature detection, never version sniffing.
	Capabilities  []string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMeta) Reset() {
	*x = AgentMeta{}
	mi := &file_kconmon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMeta) ProtoMessage() {}

func (x *AgentMeta) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMeta.ProtoReflect.Descriptor instead.
func (*AgentMeta) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentMeta) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AgentMeta) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AgentMeta) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *AgentMeta) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *AgentMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentMeta) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentMeta             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_kconmon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetAgent() *AgentMeta {
	if x != nil {
		return x.Agent
	}
	return nil
}

type RegisterResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AgentId    string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Peers      []*AgentMeta           `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	ServerTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// agent is the resolved metadata for the registering agent (e.g. zone
	// enriched by the controller from the node's failure-domain label).
	Agent         *AgentMeta `protobuf:"bytes,4,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_kconmon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetPeers() []*AgentMeta {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RegisterResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *RegisterResponse) GetAgent() *AgentMeta {
	if x != nil {
		return x.Agent
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_kconmon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type WatchPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPeersRequest) Reset() {
	*x = WatchPeersRequest{}
	mi := &file_kconmon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPeersRequest) ProtoMessage() {}

func (x *WatchPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPeersRequest.ProtoReflect.Descriptor instead.
func (*WatchPeersRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{4}
}

func (x *WatchPeersRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_kconmon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{5}
}

func (x *DeregisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type PeerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PeerUpdate_UpdateType  `protobuf:"varint,1,opt,name=type,proto3,enum=kconmonng.v1.PeerUpdate_UpdateType" json:"type,omitempty"`
	Peers         []*AgentMeta           `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUpdate) Reset() {
	*x = PeerUpdate{}
	mi := &file_kconmon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUpdate) ProtoMessage() {}

func (x *PeerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUpdate.ProtoReflect.Descriptor instead.
func (*PeerUpdate) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{6}
}

func (x *PeerUpdate) GetType() PeerUpdate_UpdateType {
	if x != nil {
		return x.Type
	}
	return PeerUpdate_FULL_SYNC
}

func (x *PeerUpdate) GetPeers() []*AgentMeta {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeerUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type WatchTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTasksRequest) Reset() {
	*x = WatchTasksRequest{}
	mi := &file_kconmon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTasksRequest) ProtoMessage() {}

func (x *WatchTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTasksRequest.ProtoReflect.Descriptor instead.
func (*WatchTasksRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{7}
}

func (x *WatchTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type WatchExternalChecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchExternalChecksRequest) Reset() {
	*x = WatchExternalChecksRequest{}
	mi := &file_kconmon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchExternalChecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchExternalChecksRequest) ProtoMessage() {}

func (x *WatchExternalChecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchExternalChecksRequest.ProtoReflect.Descriptor instead.
func (*WatchExternalChecksRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{8}
}

func (x *WatchExternalChecksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// ExternalCheckSpec is one continuous probe an agent must run. mtr and udp
// are deliberately absent from check_type: UDP's probe is a peer-to-peer
// protocol against another agent's probe server, which no external host
// runs, and a continuous MTR against an internet destination is a traffic
// and cardinality decision (mtr_hop_rtt_seconds is labelled by hop_ip,
// unbounded for internet paths) that belongs with the M5 MTR Explorer.
// One-shot MTR to a target still works through diagnostics v2.
type ExternalCheckSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefinitionId  string                 `protobuf:"bytes,1,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"` // correlation only -- NEVER a metric label
	Target        *ExternalTarget        `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	CheckType     string                 `protobuf:"bytes,3,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"` // tcp|icmp|dns|http
	IntervalNs    int64                  `protobuf:"varint,4,opt,name=interval_ns,json=intervalNs,proto3" json:"interval_ns,omitempty"`
	TimeoutNs     int64                  `protobuf:"varint,5,opt,name=timeout_ns,json=timeoutNs,proto3" json:"timeout_ns,omitempty"`
	ParamsJson    []byte                 `protobuf:"bytes,6,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"` // check-type params, agent-validated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalCheckSpec) Reset() {
	*x = ExternalCheckSpec{}
	mi := &file_kconmon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCheckSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCheckSpec) ProtoMessage() {}

func (x *ExternalCheckSpec) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalCheckSpec.ProtoReflect.Descriptor instead.
func (*ExternalCheckSpec) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{9}
}

func (x *ExternalCheckSpec) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *ExternalCheckSpec) GetTarget() *ExternalTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ExternalCheckSpec) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *ExternalCheckSpec) GetIntervalNs() int64 {
	if x != nil {
		return x.IntervalNs
	}
	return 0
}

func (x *ExternalCheckSpec) GetTimeoutNs() int64 {
	if x != nil {
		return x.TimeoutNs
	}
	return 0
}

func (x *ExternalCheckSpec) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

// ExternalCheckAssignment is the agent's COMPLETE continuous assignment --
// absolute, never a delta, same reasoning as TaskRequest.external_target's
// exclusivity comment and PeerUpdate.FULL_SYNC.
type ExternalCheckAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specs         []*ExternalCheckSpec   `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalCheckAssignment) Reset() {
	*x = ExternalCheckAssignment{}
	mi := &file_kconmon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCheckAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCheckAssignment) ProtoMessage() {}

func (x *ExternalCheckAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalCheckAssignment.ProtoReflect.Descriptor instead.
func (*ExternalCheckAssignment) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{10}
}

func (x *ExternalCheckAssignment) GetSpecs() []*ExternalCheckSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *ExternalCheckAssignment) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ExternalTarget is a probe destination that is NOT a registered agent:
// an operator-defined target, or an ad-hoc address typed into the
// diagnostics form. name is the ONLY field that becomes a metric label
// value (see docs/metrics.md); address never does.
type ExternalTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // host | url
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"` // 0 = check-type default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalTarget) Reset() {
	*x = ExternalTarget{}
	mi := &file_kconmon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalTarget) ProtoMessage() {}

func (x *ExternalTarget) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalTarget.ProtoReflect.Descriptor instead.
func (*ExternalTarget) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{11}
}

func (x *ExternalTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalTarget) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExternalTarget) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ExternalTarget) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TaskRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TaskId    string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CheckType string                 `protobuf:"bytes,2,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"` // tcp|udp|icmp|dns|http|mtr
	Target    *AgentMeta             `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Plane     string                 `protobuf:"bytes,4,opt,name=plane,proto3" json:"plane,omitempty"` // pod|host
	// external_target is set INSTEAD OF target (field 3) when the destination
	// is not a registered agent. Exactly one of the two is ever populated; the
	// agent treats both-set as a malformed request and reports an error result
	// rather than guessing. The exclusion is deliberately NOT a oneof: moving
	// the existing field 3 into a new oneof would change the generated Go API
	// and churn every existing call site for no wire benefit, so it is
	// enforced in code and tested instead.
	ExternalTarget *ExternalTarget `protobuf:"bytes,5,opt,name=external_target,json=externalTarget,proto3" json:"external_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_kconmon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{12}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *TaskRequest) GetTarget() *AgentMeta {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *TaskRequest) GetPlane() string {
	if x != nil {
		return x.Plane
	}
	return ""
}

func (x *TaskRequest) GetExternalTarget() *ExternalTarget {
	if x != nil {
		return x.ExternalTarget
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	DetailsJson   []byte                 `protobuf:"bytes,5,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"` // serialized model.CheckResult
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_kconmon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{13}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetDetailsJson() []byte {
	if x != nil {
		return x.DetailsJson
	}
	return nil
}

func (x *TaskResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TCPProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceAgentId string                 `protobuf:"bytes,1,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPProbeRequest) Reset() {
	*x = TCPProbeRequest{}
	mi := &file_kconmon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPProbeRequest) ProtoMessage() {}

func (x *TCPProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPProbeRequest.ProtoReflect.Descriptor instead.
func (*TCPProbeRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{14}
}

func (x *TCPProbeRequest) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *TCPProbeRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TCPProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPProbeResponse) Reset() {
	*x = TCPProbeResponse{}
	mi := &file_kconmon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPProbeResponse) ProtoMessage() {}

func (x *TCPProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPProbeResponse.ProtoReflect.Descriptor instead.
func (*TCPProbeResponse) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{15}
}

func (x *TCPProbeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TCPProbeResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UDPProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceAgentId string                 `protobuf:"bytes,1,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	Sequence      uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPProbeRequest) Reset() {
	*x = UDPProbeRequest{}
	mi := &file_kconmon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPProbeRequest) ProtoMessage() {}

func (x *UDPProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPProbeRequest.ProtoReflect.Descriptor instead.
func (*UDPProbeRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{16}
}

func (x *UDPProbeRequest) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *UDPProbeRequest) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *UDPProbeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UDPProbeRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UDPProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint32                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPProbeResponse) Reset() {
	*x = UDPProbeResponse{}
	mi := &file_kconmon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPProbeResponse) ProtoMessage() {}

func (x *UDPProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPProbeResponse.ProtoReflect.Descriptor instead.
func (*UDPProbeResponse) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{17}
}

func (x *UDPProbeResponse) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *UDPProbeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UDPProbeResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type WatchEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reserved for a future resume-by-seq capability across controller
	// restarts. The controller keeps no cross-restart event history in M2, so
	// this is currently unused; the field exists so the wire shape does not
	// need to change when that lands.
	LastSeq       uint64 `protobuf:"varint,1,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_kconmon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{18}
}

func (x *WatchEventsRequest) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Seq       uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_TopologyChanged
	//	*Event_CheckObserved
	//	*Event_MtrTriggered
	//	*Event_MtrCompleted
	//	*Event_DiagnosticProgress
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_kconmon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{19}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTopologyChanged() *TopologyChanged {
	if x != nil {
		if x, ok := x.Payload.(*Event_TopologyChanged); ok {
			return x.TopologyChanged
		}
	}
	return nil
}

func (x *Event) GetCheckObserved() *CheckObserved {
	if x != nil {
		if x, ok := x.Payload.(*Event_CheckObserved); ok {
			return x.CheckObserved
		}
	}
	return nil
}

func (x *Event) GetMtrTriggered() *MTRTriggered {
	if x != nil {
		if x, ok := x.Payload.(*Event_MtrTriggered); ok {
			return x.MtrTriggered
		}
	}
	return nil
}

func (x *Event) GetMtrCompleted() *MTRCompleted {
	if x != nil {
		if x, ok := x.Payload.(*Event_MtrCompleted); ok {
			return x.MtrCompleted
		}
	}
	return nil
}

func (x *Event) GetDiagnosticProgress() *DiagnosticProgress {
	if x != nil {
		if x, ok := x.Payload.(*Event_DiagnosticProgress); ok {
			return x.DiagnosticProgress
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_TopologyChanged struct {
	TopologyChanged *TopologyChanged `protobuf:"bytes,3,opt,name=topology_changed,json=topologyChanged,proto3,oneof"`
}

type Event_CheckObserved struct {
	CheckObserved *CheckObserved `protobuf:"bytes,4,opt,name=check_observed,json=checkObserved,proto3,oneof"`
}

type Event_MtrTriggered struct {
	MtrTriggered *MTRTriggered `protobuf:"bytes,5,opt,name=mtr_triggered,json=mtrTriggered,proto3,oneof"`
}

type Event_MtrCompleted struct {
	MtrCompleted *MTRCompleted `protobuf:"bytes,6,opt,name=mtr_completed,json=mtrCompleted,proto3,oneof"`
}

type Event_DiagnosticProgress struct {
	DiagnosticProgress *DiagnosticProgress `protobuf:"bytes,7,opt,name=diagnostic_progress,json=diagnosticProgress,proto3,oneof"`
}

func (*Event_TopologyChanged) isEvent_Payload() {}

func (*Event_CheckObserved) isEvent_Payload() {}

func (*Event_MtrTriggered) isEvent_Payload() {}

func (*Event_MtrCompleted) isEvent_Payload() {}

func (*Event_DiagnosticProgress) isEvent_Payload() {}

// TopologyChanged is a lightweight "refetch" signal, not a full snapshot: the
// Console already has an authoritative HTTP topology endpoint
// (GET /api/v1/topology) and re-queries it rather than duplicating node/zone
// enrichment logic in the event stream.
type TopologyChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // agent_registered|zone_updated|agent_deregistered|agent_evicted
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyChanged) Reset() {
	*x = TopologyChanged{}
	mi := &file_kconmon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyChanged) ProtoMessage() {}

func (x *TopologyChanged) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyChanged.ProtoReflect.Descriptor instead.
func (*TopologyChanged) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{20}
}

func (x *TopologyChanged) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TopologyChanged) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TopologyChanged) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// CheckObserved reports the outcome of a completed ON-DEMAND diagnostic check
// (POST /api/v1/diagnostics). It is NOT the continuous background probes —
// those go straight from agent to Prometheus and never touch the controller.
// It is a compact rollup, never the raw CheckResult payload.
type CheckObserved struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CheckType       string                 `protobuf:"bytes,2,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"` // tcp|udp|icmp|dns|http (mtr uses MTRTriggered/MTRCompleted instead)
	SourceNode      string                 `protobuf:"bytes,3,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	DestinationNode string                 `protobuf:"bytes,4,opt,name=destination_node,json=destinationNode,proto3" json:"destination_node,omitempty"`
	Plane           string                 `protobuf:"bytes,5,opt,name=plane,proto3" json:"plane,omitempty"`
	Success         bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	DurationNs      int64                  `protobuf:"varint,7,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	Error           string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckObserved) Reset() {
	*x = CheckObserved{}
	mi := &file_kconmon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckObserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckObserved) ProtoMessage() {}

func (x *CheckObserved) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckObserved.ProtoReflect.Descriptor instead.
func (*CheckObserved) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{21}
}

func (x *CheckObserved) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CheckObserved) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *CheckObserved) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *CheckObserved) GetDestinationNode() string {
	if x != nil {
		return x.DestinationNode
	}
	return ""
}

func (x *CheckObserved) GetPlane() string {
	if x != nil {
		return x.Plane
	}
	return ""
}

func (x *CheckObserved) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckObserved) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *CheckObserved) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MTRTriggered struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SourceNode      string                 `protobuf:"bytes,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	DestinationNode string                 `protobuf:"bytes,3,opt,name=destination_node,json=destinationNode,proto3" json:"destination_node,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MTRTriggered) Reset() {
	*x = MTRTriggered{}
	mi := &file_kconmon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MTRTriggered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTRTriggered) ProtoMessage() {}

func (x *MTRTriggered) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTRTriggered.ProtoReflect.Descriptor instead.
func (*MTRTriggered) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{22}
}

func (x *MTRTriggered) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MTRTriggered) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *MTRTriggered) GetDestinationNode() string {
	if x != nil {
		return x.DestinationNode
	}
	return ""
}

type MTRHop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	RttNs         int64                  `protobuf:"varint,4,opt,name=rtt_ns,json=rttNs,proto3" json:"rtt_ns,omitempty"`
	LossRatio     float64                `protobuf:"fixed64,5,opt,name=loss_ratio,json=lossRatio,proto3" json:"loss_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MTRHop) Reset() {
	*x = MTRHop{}
	mi := &file_kconmon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MTRHop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTRHop) ProtoMessage() {}

func (x *MTRHop) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTRHop.ProtoReflect.Descriptor instead.
func (*MTRHop) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{23}
}

func (x *MTRHop) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *MTRHop) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MTRHop) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MTRHop) GetRttNs() int64 {
	if x != nil {
		return x.RttNs
	}
	return 0
}

func (x *MTRHop) GetLossRatio() float64 {
	if x != nil {
		return x.LossRatio
	}
	return 0
}

type MTRCompleted struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SourceNode      string                 `protobuf:"bytes,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	DestinationNode string                 `protobuf:"bytes,3,opt,name=destination_node,json=destinationNode,proto3" json:"destination_node,omitempty"`
	Success         bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Hops            []*MTRHop              `protobuf:"bytes,6,rep,name=hops,proto3" json:"hops,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MTRCompleted) Reset() {
	*x = MTRCompleted{}
	mi := &file_kconmon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MTRCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTRCompleted) ProtoMessage() {}

func (x *MTRCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTRCompleted.ProtoReflect.Descriptor instead.
func (*MTRCompleted) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{24}
}

func (x *MTRCompleted) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MTRCompleted) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *MTRCompleted) GetDestinationNode() string {
	if x != nil {
		return x.DestinationNode
	}
	return ""
}

func (x *MTRCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MTRCompleted) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MTRCompleted) GetHops() []*MTRHop {
	if x != nil {
		return x.Hops
	}
	return nil
}

// DiagnosticProgress fires at dispatch-start and on non-terminal-failure
// paths; the terminal success outcome is a CheckObserved or MTRCompleted
// instead, never a second DiagnosticProgress.
type DiagnosticProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CheckType       string                 `protobuf:"bytes,2,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"`
	SourceNode      string                 `protobuf:"bytes,3,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	DestinationNode string                 `protobuf:"bytes,4,opt,name=destination_node,json=destinationNode,proto3" json:"destination_node,omitempty"`
	State           string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"` // dispatched|timeout|error
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiagnosticProgress) Reset() {
	*x = DiagnosticProgress{}
	mi := &file_kconmon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticProgress) ProtoMessage() {}

func (x *DiagnosticProgress) ProtoReflect() protoreflect.Message {
	mi := &file_kconmon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticProgress.ProtoReflect.Descriptor instead.
func (*DiagnosticProgress) Descriptor() ([]byte, []int) {
	return file_kconmon_proto_rawDescGZIP(), []int{25}
}

func (x *DiagnosticProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DiagnosticProgress) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *DiagnosticProgress) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *DiagnosticProgress) GetDestinationNode() string {
	if x != nil {
		return x.DestinationNode
	}
	return ""
}

func (x *DiagnosticProgress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_kconmon_proto protoreflect.FileDescriptor

const file_kconmon_proto_rawDesc = "" +
	"\n" +
	"\rkconmon.proto\x12\fkconmonng.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x02\n" +
	"\tAgentMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x15\n" +
	"\x06pod_ip\x18\x04 \x01(\tR\x05podIp\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\tR\x04zone\x12;\n" +
	"\x06labels\x18\x06 \x03(\v2#.kconmonng.v1.AgentMeta.LabelsEntryR\x06labels\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x0fRegisterRequest\x12-\n" +
	"\x05agent\x18\x01 \x01(\v2\x17.kconmonng.v1.AgentMetaR\x05agent\"\xc8\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12-\n" +
	"\x05peers\x18\x02 \x03(\v2\x17.kconmonng.v1.AgentMetaR\x05peers\x12;\n" +
	"\vserver_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12-\n" +
	"\x05agent\x18\x04 \x01(\v2\x17.kconmonng.v1.AgentMetaR\x05agent\"g\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\".\n" +
	"\x11WatchPeersRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\".\n" +
	"\x11DeregisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xed\x01\n" +
	"\n" +
	"PeerUpdate\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.kconmonng.v1.PeerUpdate.UpdateTypeR\x04type\x12-\n" +
	"\x05peers\x18\x02 \x03(\v2\x17.kconmonng.v1.AgentMetaR\x05peers\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"=\n" +
	"\n" +
	"UpdateType\x12\r\n" +
	"\tFULL_SYNC\x10\x00\x12\x0e\n" +
	"\n" +
	"PEER_ADDED\x10\x01\x12\x10\n" +
	"\fPEER_REMOVED\x10\x02\".\n" +
	"\x11WatchTasksRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"7\n" +
	"\x1aWatchExternalChecksRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xee\x01\n" +
	"\x11ExternalCheckSpec\x12#\n" +
	"\rdefinition_id\x18\x01 \x01(\tR\fdefinitionId\x124\n" +
	"\x06target\x18\x02 \x01(\v2\x1c.kconmonng.v1.ExternalTargetR\x06target\x12\x1d\n" +
	"\n" +
	"check_type\x18\x03 \x01(\tR\tcheckType\x12\x1f\n" +
	"\vinterval_ns\x18\x04 \x01(\x03R\n" +
	"intervalNs\x12\x1d\n" +
	"\n" +
	"timeout_ns\x18\x05 \x01(\x03R\ttimeoutNs\x12\x1f\n" +
	"\vparams_json\x18\x06 \x01(\fR\n" +
	"paramsJson\"\x8a\x01\n" +
	"\x17ExternalCheckAssignment\x125\n" +
	"\x05specs\x18\x01 \x03(\v2\x1f.kconmonng.v1.ExternalCheckSpecR\x05specs\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"f\n" +
	"\x0eExternalTarget\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\"\xd3\x01\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"check_type\x18\x02 \x01(\tR\tcheckType\x12/\n" +
	"\x06target\x18\x03 \x01(\v2\x17.kconmonng.v1.AgentMetaR\x06target\x12\x14\n" +
	"\x05plane\x18\x04 \x01(\tR\x05plane\x12E\n" +
	"\x0fexternal_target\x18\x05 \x01(\v2\x1c.kconmonng.v1.ExternalTargetR\x0eexternalTarget\"\xcd\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12!\n" +
	"\fdetails_json\x18\x05 \x01(\fR\vdetailsJson\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"s\n" +
	"\x0fTCPProbeRequest\x12&\n" +
	"\x0fsource_agent_id\x18\x01 \x01(\tR\rsourceAgentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\\\n" +
	"\x10TCPProbeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa9\x01\n" +
	"\x0fUDPProbeRequest\x12&\n" +
	"\x0fsource_agent_id\x18\x01 \x01(\tR\rsourceAgentId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x82\x01\n" +
	"\x10UDPProbeResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"/\n" +
	"\x12WatchEventsRequest\x12\x19\n" +
	"\blast_seq\x18\x01 \x01(\x04R\alastSeq\"\xcb\x03\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12J\n" +
	"\x10topology_changed\x18\x03 \x01(\v2\x1d.kconmonng.v1.TopologyChangedH\x00R\x0ftopologyChanged\x12D\n" +
	"\x0echeck_observed\x18\x04 \x01(\v2\x1b.kconmonng.v1.CheckObservedH\x00R\rcheckObserved\x12A\n" +
	"\rmtr_triggered\x18\x05 \x01(\v2\x1a.kconmonng.v1.MTRTriggeredH\x00R\fmtrTriggered\x12A\n" +
	"\rmtr_completed\x18\x06 \x01(\v2\x1a.kconmonng.v1.MTRCompletedH\x00R\fmtrCompleted\x12S\n" +
	"\x13diagnostic_progress\x18\a \x01(\v2 .kconmonng.v1.DiagnosticProgressH\x00R\x12diagnosticProgressB\t\n" +
	"\apayload\"a\n" +
	"\x0fTopologyChanged\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"\xfa\x01\n" +
	"\rCheckObserved\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"check_type\x18\x02 \x01(\tR\tcheckType\x12\x1f\n" +
	"\vsource_node\x18\x03 \x01(\tR\n" +
	"sourceNode\x12)\n" +
	"\x10destination_node\x18\x04 \x01(\tR\x0fdestinationNode\x12\x14\n" +
	"\x05plane\x18\x05 \x01(\tR\x05plane\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x1f\n" +
	"\vduration_ns\x18\a \x01(\x03R\n" +
	"durationNs\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"s\n" +
	"\fMTRTriggered\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\tR\n" +
	"sourceNode\x12)\n" +
	"\x10destination_node\x18\x03 \x01(\tR\x0fdestinationNode\"\x82\x01\n" +
	"\x06MTRHop\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x15\n" +
	"\x06rtt_ns\x18\x04 \x01(\x03R\x05rttNs\x12\x1d\n" +
	"\n" +
	"loss_ratio\x18\x05 \x01(\x01R\tlossRatio\"\xcd\x01\n" +
	"\fMTRCompleted\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\tR\n" +
	"sourceNode\x12)\n" +
	"\x10destination_node\x18\x03 \x01(\tR\x0fdestinationNode\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12(\n" +
	"\x04hops\x18\x06 \x03(\v2\x14.kconmonng.v1.MTRHopR\x04hops\"\xae\x01\n" +
	"\x12DiagnosticProgress\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"check_type\x18\x02 \x01(\tR\tcheckType\x12\x1f\n" +
	"\vsource_node\x18\x03 \x01(\tR\n" +
	"sourceNode\x12)\n" +
	"\x10destination_node\x18\x04 \x01(\tR\x0fdestinationNode\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state2\xad\x04\n" +
	"\rAgentRegistry\x12I\n" +
	"\bRegister\x12\x1d.kconmonng.v1.RegisterRequest\x1a\x1e.kconmonng.v1.RegisterResponse\x12C\n" +
	"\tHeartbeat\x12\x1e.kconmonng.v1.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\n" +
	"WatchPeers\x12\x1f.kconmonng.v1.WatchPeersRequest\x1a\x18.kconmonng.v1.PeerUpdate0\x01\x12E\n" +
	"\n" +
	"Deregister\x12\x1f.kconmonng.v1.DeregisterRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\n" +
	"WatchTasks\x12\x1f.kconmonng.v1.WatchTasksRequest\x1a\x19.kconmonng.v1.TaskRequest0\x01\x12D\n" +
	"\x10ReportTaskResult\x12\x18.kconmonng.v1.TaskResult\x1a\x16.google.protobuf.Empty\x12h\n" +
	"\x13WatchExternalChecks\x12(.kconmonng.v1.WatchExternalChecksRequest\x1a%.kconmonng.v1.ExternalCheckAssignment0\x012\xa4\x01\n" +
	"\fProbeService\x12I\n" +
	"\bTCPProbe\x12\x1d.kconmonng.v1.TCPProbeRequest\x1a\x1e.kconmonng.v1.TCPProbeResponse\x12I\n" +
	"\bUDPProbe\x12\x1d.kconmonng.v1.UDPProbeRequest\x1a\x1e.kconmonng.v1.UDPProbeResponse2U\n" +
	"\vEventStream\x12F\n" +
	"\vWatchEvents\x12 .kconmonng.v1.WatchEventsRequest\x1a\x13.kconmonng.v1.Event0\x01B1Z/github.com/EsDmitrii/kconmon-ng/api/proto;protob\x06proto3"

var (
	file_kconmon_proto_rawDescOnce sync.Once
	file_kconmon_proto_rawDescData []byte
)

func file_kconmon_proto_rawDescGZIP() []byte {
	file_kconmon_proto_rawDescOnce.Do(func() {
		file_kconmon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kconmon_proto_rawDesc), len(file_kconmon_proto_rawDesc)))
	})
	return file_kconmon_proto_rawDescData
}

var file_kconmon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kconmon_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_kconmon_proto_goTypes = []any{
	(PeerUpdate_UpdateType)(0),         // 0: kconmonng.v1.PeerUpdate.UpdateType
	(*AgentMeta)(nil),                  // 1: kconmonng.v1.AgentMeta
	(*RegisterRequest)(nil),            // 2: kconmonng.v1.RegisterRequest
	(*RegisterResponse)(nil),           // 3: kconmonng.v1.RegisterResponse
	(*HeartbeatRequest)(nil),           // 4: kconmonng.v1.HeartbeatRequest
	(*WatchPeersRequest)(nil),          // 5: kconmonng.v1.WatchPeersRequest
	(*DeregisterRequest)(nil),          // 6: kconmonng.v1.DeregisterRequest
	(*PeerUpdate)(nil),                 // 7: kconmonng.v1.PeerUpdate
	(*WatchTasksRequest)(nil),          // 8: kconmonng.v1.WatchTasksRequest
	(*WatchExternalChecksRequest)(nil), // 9: kconmonng.v1.WatchExternalChecksRequest
	(*ExternalCheckSpec)(nil),          // 10: kconmonng.v1.ExternalCheckSpec
	(*ExternalCheckAssignment)(nil),    // 11: kconmonng.v1.ExternalCheckAssignment
	(*ExternalTarget)(nil),             // 12: kconmonng.v1.ExternalTarget
	(*TaskRequest)(nil),                // 13: kconmonng.v1.TaskRequest
	(*TaskResult)(nil),                 // 14: kconmonng.v1.TaskResult
	(*TCPProbeRequest)(nil),            // 15: kconmonng.v1.TCPProbeRequest
	(*TCPProbeResponse)(nil),           // 16: kconmonng.v1.TCPProbeResponse
	(*UDPProbeRequest)(nil),            // 17: kconmonng.v1.UDPProbeRequest
	(*UDPProbeResponse)(nil),           // 18: kconmonng.v1.UDPProbeResponse
	(*WatchEventsRequest)(nil),         // 19: kconmonng.v1.WatchEventsRequest
	(*Event)(nil),                      // 20: kconmonng.v1.Event
	(*TopologyChanged)(nil),            // 21: kconmonng.v1.TopologyChanged
	(*CheckObserved)(nil),              // 22: kconmonng.v1.CheckObserved
	(*MTRTriggered)(nil),               // 23: kconmonng.v1.MTRTriggered
	(*MTRHop)(nil),                     // 24: kconmonng.v1.MTRHop
	(*MTRCompleted)(nil),               // 25: kconmonng.v1.MTRCompleted
	(*DiagnosticProgress)(nil),         // 26: kconmonng.v1.DiagnosticProgress
	nil,                                // 27: kconmonng.v1.AgentMeta.LabelsEntry
	(*timestamppb.Timestamp)(nil),      // 28: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 29: google.protobuf.Empty
}
var file_kconmon_proto_depIdxs = []int32{
	27, // 0: kconmonng.v1.AgentMeta.labels:type_name -> kconmonng.v1.AgentMeta.LabelsEntry
	1,  // 1: kconmonng.v1.RegisterRequest.agent:type_name -> kconmonng.v1.AgentMeta
	1,  // 2: kconmonng.v1.RegisterResponse.peers:type_name -> kconmonng.v1.AgentMeta
	28, // 3: kconmonng.v1.RegisterResponse.server_time:type_name -> google.protobuf.Timestamp
	1,  // 4: kconmonng.v1.RegisterResponse.agent:type_name -> kconmonng.v1.AgentMeta
	28, // 5: kconmonng.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: kconmonng.v1.PeerUpdate.type:type_name -> kconmonng.v1.PeerUpdate.UpdateType
	1,  // 7: kconmonng.v1.PeerUpdate.peers:type_name -> kconmonng.v1.AgentMeta
	28, // 8: kconmonng.v1.PeerUpdate.timestamp:type_name -> google.protobuf.Timestamp
	12, // 9: kconmonng.v1.ExternalCheckSpec.target:type_name -> kconmonng.v1.ExternalTarget
	10, // 10: kconmonng.v1.ExternalCheckAssignment.specs:type_name -> kconmonng.v1.ExternalCheckSpec
	28, // 11: kconmonng.v1.ExternalCheckAssignment.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 12: kconmonng.v1.TaskRequest.target:type_name -> kconmonng.v1.AgentMeta
	12, // 13: kconmonng.v1.TaskRequest.external_target:type_name -> kconmonng.v1.ExternalTarget
	28, // 14: kconmonng.v1.TaskResult.timestamp:type_name -> google.protobuf.Timestamp
	28, // 15: kconmonng.v1.TCPProbeRequest.timestamp:type_name -> google.protobuf.Timestamp
	28, // 16: kconmonng.v1.TCPProbeResponse.timestamp:type_name -> google.protobuf.Timestamp
	28, // 17: kconmonng.v1.UDPProbeRequest.timestamp:type_name -> google.protobuf.Timestamp
	28, // 18: kconmonng.v1.UDPProbeResponse.timestamp:type_name -> google.protobuf.Timestamp
	28, // 19: kconmonng.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	21, // 20: kconmonng.v1.Event.topology_changed:type_name -> kconmonng.v1.TopologyChanged
	22, // 21: kconmonng.v1.Event.check_observed:type_name -> kconmonng.v1.CheckObserved
	23, // 22: kconmonng.v1.Event.mtr_triggered:type_name -> kconmonng.v1.MTRTriggered
	25, // 23: kconmonng.v1.Event.mtr_completed:type_name -> kconmonng.v1.MTRCompleted
	26, // 24: kconmonng.v1.Event.diagnostic_progress:type_name -> kconmonng.v1.DiagnosticProgress
	24, // 25: kconmonng.v1.MTRCompleted.hops:type_name -> kconmonng.v1.MTRHop
	2,  // 26: kconmonng.v1.AgentRegistry.Register:input_type -> kconmonng.v1.RegisterRequest
	4,  // 27: kconmonng.v1.AgentRegistry.Heartbeat:input_type -> kconmonng.v1.HeartbeatRequest
	5,  // 28: kconmonng.v1.AgentRegistry.WatchPeers:input_type -> kconmonng.v1.WatchPeersRequest
	6,  // 29: kconmonng.v1.AgentRegistry.Deregister:input_type -> kconmonng.v1.DeregisterRequest
	8,  // 30: kconmonng.v1.AgentRegistry.WatchTasks:input_type -> kconmonng.v1.WatchTasksRequest
	14, // 31: kconmonng.v1.AgentRegistry.ReportTaskResult:input_type -> kconmonng.v1.TaskResult
	9,  // 32: kconmonng.v1.AgentRegistry.WatchExternalChecks:input_type -> kconmonng.v1.WatchExternalChecksRequest
	15, // 33: kconmonng.v1.ProbeService.TCPProbe:input_type -> kconmonng.v1.TCPProbeRequest
	17, // 34: kconmonng.v1.ProbeService.UDPProbe:input_type -> kconmonng.v1.UDPProbeRequest
	19, // 35: kconmonng.v1.EventStream.WatchEvents:input_type -> kconmonng.v1.WatchEventsRequest
	3,  // 36: kconmonng.v1.AgentRegistry.Register:output_type -> kconmonng.v1.RegisterResponse
	29, // 37: kconmonng.v1.AgentRegistry.Heartbeat:output_type -> google.protobuf.Empty
	7,  // 38: kconmonng.v1.AgentRegistry.WatchPeers:output_type -> kconmonng.v1.PeerUpdate
	29, // 39: kconmonng.v1.AgentRegistry.Deregister:output_type -> google.protobuf.Empty
	13, // 40: kconmonng.v1.AgentRegistry.WatchTasks:output_type -> kconmonng.v1.TaskRequest
	29, // 41: kconmonng.v1.AgentRegistry.ReportTaskResult:output_type -> google.protobuf.Empty
	11, // 42: kconmonng.v1.AgentRegistry.WatchExternalChecks:output_type -> kconmonng.v1.ExternalCheckAssignment
	16, // 43: kconmonng.v1.ProbeService.TCPProbe:output_type -> kconmonng.v1.TCPProbeResponse
	18, // 44: kconmonng.v1.ProbeService.UDPProbe:output_type -> kconmonng.v1.UDPProbeResponse
	20, // 45: kconmonng.v1.EventStream.WatchEvents:output_type -> kconmonng.v1.Event
	36, // [36:46] is the sub-list for method output_type
	26, // [26:36] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_kconmon_proto_init() }
func file_kconmon_proto_init() {
	if File_kconmon_proto != nil {
		return
	}
	file_kconmon_proto_msgTypes[19].OneofWrappers = []any{
		(*Event_TopologyChanged)(nil),
		(*Event_CheckObserved)(nil),
		(*Event_MtrTriggered)(nil),
		(*Event_MtrCompleted)(nil),
		(*Event_DiagnosticProgress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kconmon_proto_rawDesc), len(file_kconmon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_kconmon_proto_goTypes,
		DependencyIndexes: file_kconmon_proto_depIdxs,
		EnumInfos:         file_kconmon_proto_enumTypes,
		MessageInfos:      file_kconmon_proto_msgTypes,
	}.Build()
	File_kconmon_proto = out.File
	file_kconmon_proto_goTypes = nil
	file_kconmon_proto_depIdxs = nil
}
