---
redis:
  existingSecret: kconmon-console-redis
database:
  existingSecret: console-db-dummy
controller:
  events:
    enabled: true
console:
  enabled: true
  replicas: 2
  kubernetesContext:
    enabled: true
    namespace: ''
    resyncInterval: 5m
  webhooks:
    existingSecret: kconmon-webhook-key
    existingSecretKey: console-webhooks-encryption-key
  prometheus:
    url: http://prometheus-operated.monitoring:9090
networkPolicy:
  enabled: true
