---
redis:
  existingSecret: kconmon-console-redis
database:
  existingSecret: kconmon-console-db
controller:
  events:
    enabled: true
console:
  enabled: true
  replicas: 2
  mtr:
    enrichment:
      enabled: true
      rdns:
        enabled: true
        timeoutMs: 250
      geoip:
        mode: volume
        asnPath: /geoip/GeoLite2-ASN.mmdb
        cityPath: /geoip/GeoLite2-City.mmdb
        volume:
          persistentVolumeClaim:
            claimName: kconmon-ng-geoip
      ttl: 12h
  prometheus:
    url: http://prometheus-operated.monitoring:9090
networkPolicy:
  enabled: true
