---
redis:
  existingSecret: kconmon-console-redis
database:
  existingSecret: console-db-dummy
console:
  enabled: true
  replicas: 2
  auth:
    mode: local
    local:
      bootstrapAdmin: admin
      existingSecret: console-local-admin-dummy
      existingSecretKey: bootstrapPassword
    defaultRole: viewer
  prometheus:
    url: http://prometheus-operated.monitoring:9090
networkPolicy:
  enabled: true
