---
redis:
  existingSecret: kconmon-console-redis
database:
  retentionDays: 30
  existingSecret: kconmon-console-db
controller:
  events:
    enabled: true
console:
  enabled: true
  replicas: 2
  prometheus:
    url: http://prometheus-operated.monitoring:9090
networkPolicy:
  enabled: true
