---
redis:
  existingSecret: kconmon-console-redis
database:
  existingSecret: console-db-dummy
controller:
  events:
    enabled: true
console:
  enabled: true
  replicas: 2
  alerting:
    enabled: true
    namespace: ''
    syncInterval: 30s
    bundleName: kconmon-ng-console-rules
  webhooks:
    existingSecret: kconmon-webhook-key
    existingSecretKey: console-webhooks-encryption-key
    alertPollInterval: 15s
  prometheus:
    url: http://prometheus-operated.monitoring:9090
networkPolicy:
  enabled: true
