{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kconmon-ng.fullname" . }}-controller
  labels:
    {{- include "kconmon-ng.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      {{- include "kconmon-ng.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
